[general]
import = [
    "~/.config/alacritty/dracula_plus.toml"
]

[window]
padding.x = 5
padding.y = 5
option_as_alt = "Both"

[window.dimensions]
columns = 120
lines = 40

[font]
normal.family = "Fira Code"
normal.style = "Regular"

bold.family = "Fira Code"
bold.style = "Bold"

italic.family = "Fira Code"
italic.style = "Italic"

bold_italic.family = "Fira Code"
bold_italic.style = "Bold Italic"
size = 16
offset.x = 1

